---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  name: registries.ml.llmos.ai
spec:
  group: ml.llmos.ai
  names:
    kind: Registry
    listKind: RegistryList
    plural: registries
    shortNames:
    - reg
    - regs
    singular: registry
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.backendType
      name: Backend
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: Registry is a cluster-level resource for managing model registries
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: RegistrySpec defines the desired state of Registry
            properties:
              backendType:
                description: BackendType is the type of backend storage (e.g., S3)
                enum:
                - S3
                type: string
              s3Config:
                properties:
                  accessCredentialSecretName:
                    description: AccessCredentialSecretName is the name of the secret
                      containing the access credentials
                    type: string
                  bucket:
                    description: Bucket is the name of the S3 bucket
                    type: string
                  endpoint:
                    description: Endpoint is the endpoint of the S3 storage
                    type: string
                  useSSL:
                    description: UseSSL indicates whether to use http or https
                    type: boolean
                required:
                - accessCredentialSecretName
                - bucket
                - endpoint
                - useSSL
                type: object
            required:
            - backendType
            type: object
          status:
            description: RegistryStatus defines the observed state of Registry
            properties:
              conditions:
                description: Conditions is a list of conditions representing the status
                  of the Registry
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    lastUpdateTime:
                      description: The last time this condition was updated.
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of the condition.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              storageAddress:
                description: StorageAddress is the address of the registry where to
                  store models and datasets
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
