---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  name: datasets.ml.llmos.ai
spec:
  group: ml.llmos.ai
  names:
    kind: Dataset
    listKind: DatasetList
    plural: datasets
    singular: dataset
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.registry
      name: Registry
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: Dataset is a definition for the LLM Dataset
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: DatasetSpec defines the desired state of Dataset
            properties:
              datasetCard:
                description: |-
                  DatasetCard contains metadata and description for a dataset
                  Reference: https://huggingface.co/docs/datasets/dataset_card
                properties:
                  description:
                    type: string
                  metadata:
                    description: DatasetMetaData is the metadata of a dataset
                    properties:
                      authors:
                        items:
                          type: string
                        type: array
                      citation:
                        type: string
                      contact:
                        type: string
                      downloadUrl:
                        type: string
                      features:
                        items:
                          type: string
                        type: array
                      homepage:
                        type: string
                      language:
                        type: string
                      license:
                        type: string
                      numSamples:
                        type: integer
                      splitTypes:
                        items:
                          type: string
                        type: array
                      tags:
                        items:
                          type: string
                        type: array
                    type: object
                required:
                - metadata
                type: object
              registry:
                type: string
            required:
            - registry
            type: object
          status:
            properties:
              conditions:
                description: Conditions is a list of conditions representing the status
                  of the Dataset
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    lastUpdateTime:
                      description: The last time this condition was updated.
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of the condition.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              path:
                description: RootPath is the root path of the dataset in the storage
                type: string
              versions:
                description: Versions is a list of versions of the dataset
                items:
                  properties:
                    objectName:
                      type: string
                    version:
                      type: string
                  required:
                  - objectName
                  - version
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
