---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  name: models.ml.llmos.ai
spec:
  group: ml.llmos.ai
  names:
    kind: Model
    listKind: ModelList
    plural: models
    singular: model
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.registry
      name: Registry
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: Model is a definition for the LLM Model
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: ModelSpec defines the desired state of Model
            properties:
              modelCard:
                description: |-
                  ModelCard contains metadata and description for a model
                  Reference: https://huggingface.co/docs/hub/models-cards
                properties:
                  description:
                    type: string
                  metadata:
                    description: ModelMetaData is the metadata of a model
                    properties:
                      baseModel:
                        type: string
                      cpu:
                        type: boolean
                      datasets:
                        items:
                          type: string
                        type: array
                      evaluationResults:
                        type: string
                      framework:
                        type: string
                      gpu:
                        type: boolean
                      language:
                        type: string
                      libraryName:
                        type: string
                      libraryVersion:
                        type: string
                      license:
                        type: string
                      metrics:
                        items:
                          type: string
                        type: array
                      tags:
                        items:
                          type: string
                        type: array
                      trainingData:
                        type: string
                    type: object
                required:
                - description
                - metadata
                type: object
              registry:
                type: string
            required:
            - registry
            type: object
          status:
            properties:
              conditions:
                description: Conditions is a list of conditions representing the status
                  of the Model
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    lastUpdateTime:
                      description: The last time this condition was updated.
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of the condition.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              path:
                description: RootPath is the root path of the model in the storage
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
