apiVersion: ml.llmos.ai/v1
kind: Model
metadata:
  name: llama-2
  namespace: default
spec:
  registry: demo-registry
  modelCard:
    description: "Llama 2 is a collection of pretrained and fine-tuned generative text models ranging in scale from 7 billion to 70 billion parameters."
    metadata:
      tags:
        - llm
        - transformer
        - decoder-only
      license: "llama2"
      datasets:
        - publicly-available-data
        - partner-data
      language: "en"
      framework: "pytorch"
      cpu: true
      gpu: true
      baseModel: "llama"
---
apiVersion: ml.llmos.ai/v1
kind: Model
metadata:
  name: llama-3
  namespace: default
spec:
  registry: demo-registry
  modelCard:
    description: "Llama 3 is a collection of pretrained and fine-tuned generative text models ranging in scale from 7 billion to 70 billion parameters."
    metadata:
      tags:
        - llm
        - transformer
        - decoder-only
      license: "llama2"
      datasets:
        - publicly-available-data
        - partner-data
      language: "en"
      framework: "pytorch"
      cpu: true
      gpu: true
      baseModel: "llama"
