apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: llmos-system
type: Opaque
data:
  # echo -n <access key id> | base64
  # use echo -n to avoid the trailing newline
  # Replace with your base64-encoded access key ID
  accessKeyID: <your-base64-encoded-access-key-id>
  # Replace with your base64-encoded access key secret
  accessKeySecret: <your-base64-encoded-access-key-secret>